---
language: node_js
before-install:
  - "npm install -g grunt-cli"

install:
  - "npm install"
  - "bower install"

cache:
  directories:
    - node_modules
    - bower_components

script:
  - grunt test
